dependencies:
- nodejs==15.*
- pip==22.2.*
- python==3.10.*
- jupyterlab==4.0.0a27
- notebook==7.0.0a5
- matplotlib==3.5.2
- ipympl==0.9.1
- pandas==1.4.3
- scipy==1.9.0
- statsmodels==0.13.2
- seaborn==0.11.2

# Items not in conda forge
- pip:
  - folium==0.12.1
  - datascience==0.17.5
  - otter_grader==3.3.0